function [run] = combinazioni(num_fattori,num_livelli)

num_analisi=num_livelli^num_fattori;

switch num_fattori
    case 2
        run=[(-1).^(1:1:num_analisi);...
        (-1).^ceil(1/2.*(1:1:num_analisi))]';
    case 3
        run=[(-1).^(1:1:num_analisi);...
            (-1).^ceil(1/2.*(1:1:num_analisi));...
            (-1).^ceil(1/4.*(1:1:num_analisi))]';
    case 4
        run=[(-1).^(1:1:num_analisi);...
            (-1).^ceil(1/2.*(1:1:num_analisi));...
            (-1).^ceil(1/4.*(1:1:num_analisi));...
            (-1).^ceil(1/8.*(1:1:num_analisi))]';
    case 5
        run=[(-1).^(1:1:num_analisi);...
            (-1).^ceil(1/2.*(1:1:num_analisi));...
            (-1).^ceil(1/4.*(1:1:num_analisi));...
            (-1).^ceil(1/8.*(1:1:num_analisi));...
            (-1).^ceil(1/16.*(1:1:num_analisi))]';
    case 6
        run=[(-1).^(1:1:num_analisi);...
            (-1).^ceil(1/2.*(1:1:num_analisi));...
            (-1).^ceil(1/4.*(1:1:num_analisi));...
            (-1).^ceil(1/8.*(1:1:num_analisi));...
            (-1).^ceil(1/16.*(1:1:num_analisi));...
            (-1).^ceil(1/32.*(1:1:num_analisi))]';
    otherwise
        error('Error occurred. Numero fattori deve essere compreso fra 2 e 6');
end

end

